### ISSUE TITLE
Query for version number of the core

### ISSUE THREAD

**Issue by teotigraphix** [teotigraphix/CausticSDK#11]
Would this be hard to do?

**Comment by causticrej** [comment]
Android / Java:
int CausticCore.nativeGetVersion()

Windows / C:
int CausticCore_GetVersion()

return a 32 bit value where the version number is split into 4 parts, 8 bits each
bits [24..31] are major version
bits [16..23] are minor version
bits [8..15] are release #
bits [0..7] are build # (though I doubt you'll ever see that change for OSC)

For example right now it returns 0x03000000 for 3.0.0.0

**Comment by teotigraphix** [comment]
commit faad58f
