### ISSUE TITLE
MultiFilter OSC

### ISSUE THREAD

**Issue by teotigraphix** [teotigraphix/CausticSDK#29]

**Comment by causticrej** [comment]
This one was copied from the ParamEQ so should be in already, but some params need to be changed like "width" for "resonance"

Right now commands are

mode [0,1,2,3,4,5] corresponding to lowshelf, highshelf, lowpass, highpass, bandpass, bandisolate
frequency [0.1 .. 1]
width [0 ..1]
gain [-12 .. 12]

**Comment by causticrej** [comment]
actually I changed "width" to "resonance" in the build I sent you so it's in line with the UI text now
