### ISSUE TITLE
8BitSynth OSC

### ISSUE THREAD

**Issue by teotigraphix** [teotigraphix/CausticSDK#30]

**Comment by causticrej** [comment]
list of commands not including the standard "note" "load_preset", etc

expression index [stringexpr] where index is 0 or 1 corresponding to ExpA or B, and stringexp is the function to evaluate. returns -1000000 if there is an error in the expression.

ab_blend [0..1]
octave [-4,-3,-2,-1,0,1,2,3,4]
semis [-12 .. 12](in integer steps)
cents [-100..100]
volume [0..2]
