### ISSUE TITLE
Vocoder OSC

### ISSUE THREAD

**Issue by teotigraphix** [teotigraphix/CausticSDK#31]

**Comment by causticrej** [comment]
Standard "note" command should work, no presets with this one.

preview_modulator [modIdx] the modulator used for live/preview playing via "note"

clear_modulator modIdx, clears all sample data and resets this modulator slot.

modulator modIdx [machine idx or WAV path]. If the param is a string it will load it as WAV, if it's a number it will use the machine at that idx as the mod. It's an error to reference itself or an empty slot. To query, be sure to use the response string. a return value of -1 indicates it's using a WAV file and the sample name will be copied to the response. If it's a machine, the return value indicates the slot# and the response is not touched.

ccontrol EQIdx [gain] EQIdx is 0,1,2,3,4,5,6,7 and gain is [-1 .. 1]

carrier_source [machine idx] ,where idx -1 == internal synth and any other number represents a machine slot. It's an error to reference itself or an empty slot.

send_notes [0,1]

waveform [0,1] corresponding to saw, square

unison [0..1]

sub [0..1]

noise [0..1]

slew [0.. 0.4]

hf_bypass [0..1]

dry [0..1]

volume_out [0..2]

I think that should cover it.
