### ISSUE TITLE
FMSynth OSC

### ISSUE THREAD

**Issue by teotigraphix** [teotigraphix/CausticSDK#32]

**Comment by causticrej** [comment]
standard preset, note, polyphony should work

new stuff:

algorithm [0,1,2,3,4] corresponding to 3->2->1, 1+(3->2), (2+3)->1, 1+2+3, (3->1)+(3->2) , good luck naming those constants ;-)

feedback [0 .. 0.25]
feedback_vel [0,1]
volume_out [0..1]
volume_vel [0,1]
lfo_a1 [0,1]
lfo_a2 [0,1]
lfo_a3 [0,1]
lfo_aOut [0,1]
lfo_f1 [0,1]
lfo_f2 [0,1]
lfo_f3 [0,1]
lfo_rate [0,1,2,3,4,5,6,7,8,9,10,11,12] same as other synths
lfo_depth [0..1]

for the operators you add the following to the address:

/ operator / idx / command  where idx is [0,1,2] corrsponding to the 3 operators, the operator commands are:

level [0..1]
level_vel [0,1]
octave [-4,-3,-2,-1,0,1,2,3,4]
fixed [0,1]
semis [-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6]
attack_exp [0,1]
attack [0..1]
decay_exp [0,1]
decay [0..1]
link [0,1]
sustain [0..1]
release_exp [0,1]
release [0..1]
