### ISSUE TITLE
Subsynth updated OSC

### ISSUE THREAD

**Issue by teotigraphix** [teotigraphix/CausticSDK#35]
- waveforms
- FM/PM/AM modulation
- cents/unison
- polyphony is Lagato 0?
- LFO1 & 2 targets
- is there a way to load custom waveforms?

**Comment by causticrej** [comment]
Changes to subsynth OSC
"osc_fm" becomes "osc_modulation"
legato is polyphony 0, I've removed the previous restriction to 1 in the lib
the waveform selectors get their values changed to the current order in the app
Same for LFOs, you can access the values in the order they appear in the app.

New:
osc_modulation_mode [0,1,2] corresponding to FM, PM, AM
osc2_cents_mode [0,1] corresponding to cents, unison

No way to load custom waveforms yet, it's 440 16bit values so the best way would probably to have the app write a temp WAV File and have the core laod the file into the waveform slot.

**Comment by teotigraphix** [comment]
commit 137150f253c02076d07240b45fb98f2c49e0fca3
