### ISSUE TITLE
Global/machine and per pattern Swing OSC

### ISSUE THREAD

**Issue by teotigraphix** [teotigraphix/CausticSDK#37]

**Comment by causticrej** [comment]
outputpanel/shuffle_mode [1,2] where 1 is 8th notes and 2 is 16th notes
outputpanel/shuffle_amount [0..1]

../pattern_sequencer/shuffle_mode [0,1,2] where 0 is "default" (use what is set in the outputpanel), 1 and 2 are overrides and use same values as above
../pattern_sequencer/shuffle_amount [0..1](has no effect if mode is 0)

**Comment by teotigraphix** [comment]
commit db3f4083f5b6d5b77e754443c6f59c6658282cc8
