### ISSUE TITLE
Updated Effect OSC

### ISSUE THREAD

**Issue by teotigraphix** [teotigraphix/CausticSDK#38]
The following have had controls added to them;

Flanger

Chorus

Phraser

**Comment by causticrej** [comment]
this adds a new "mode" command for flanger, chorus and static flanger (this will be in the next build)

in the case of chorus/flanger
mode [0,1,2,3,4,5,6,7] corresponding to 

triangleFull, sineFull, triangleHalf, sineHalf, triangleFullOpposed, sineFullOpposed, triangleHalfOpposed, sineHalfOpposed

in the case of static flanger

mode [0,4] corresponding to triangleFull, triangleFullOpposed

new for Phaser (these are in already)

lowfreq [0.002 .. 0.5]
highfreq [0.002 .. 0.5]
