### ISSUE TITLE
Change pattern_sequencer calls to be prefixed with bank and pattern

### ISSUE THREAD

**Issue by teotigraphix** [teotigraphix/CausticSDK#41]
By doing this, operations on the non current/active pattern is possible, also removes 1/3 of code dealing with switching patterns.

So; /caustic/0/pattern_sequencer [bank] [pattern] .... normal osc messages for it

**Comment by causticrej** [comment]
should be possible, I might need to change a bunch of code on my side though, this isn't a simple change.

**Comment by teotigraphix** [comment]
Ok but this isn't a priority for me right now so it can be back burner.
