### ISSUE TITLE
pattern_sequencer start at position

### ISSUE THREAD

**Issue by teotigraphix** [teotigraphix/CausticSDK#44]
Is it possible to start the pattern sequencer at a specified beat like the song sequencer does?

I have a couple use cases this could benefit from.

**Comment by causticrej** [comment]
I don't support this in the app yet so this would have to be added, let me know how high a priority this is (compared to the rest of the list)

**Comment by teotigraphix** [comment]
it only had todo with Caustic Live and changing patterns and starting 
mid way but I have changed things to use the song sequencer more. It 
would be nice but not necessary.
