### ISSUE TITLE
Piano Roll OSC command

### ISSUE THREAD

**Issue by teotigraphix** [teotigraphix/CausticSDK#46]
OSC read/write command for the Song sequencer piano roll note data.

**Comment by causticrej** [comment]
yeah we talked about this ages ago, I'll see what I can do.

**Comment by teotigraphix** [comment]
Ok, great! query and send would be kewl. Maybe to avoid buffer issues, make it a machine command, so I get it for each machine in different calls.

**Comment by teotigraphix** [comment]
Impl
