### ISSUE TITLE
Effect OSC needs bypass message

### ISSUE THREAD

**Issue by teotigraphix** [teotigraphix/CausticSDK#47]
we have bypass in master components but not individual effect message

Where we have ; `/caustic/effects_rack/[machine_index]/[slot]/[control] [value]`

for the SET command, I guess it would look like;

`/caustic/effects_rack/0/0/bypass 1`

**Comment by causticrej** [comment]
this works already because the bypass is just another control

I tested on a few effects but I'm sure your testsuite will check them all.
