### ISSUE TITLE
8BitSynth query expression returns empty string

### ISSUE THREAD

**Issue by teotigraphix** [teotigraphix/CausticSDK#52]

**Comment by causticrej** [comment]
this will be fixed along with the spaces fix for paths

**Comment by teotigraphix** [comment]
@causticrej 

`/caustic/0/expression 0` query returns "", 

did you change something, because before it DID return the correct value, the tests are now failing.

**Comment by causticrej** [comment]
I just tried a preset "alarm arp" and it worked on windows. Any particular preset it's failing on or are you create it from OSC as well in your tests?

**Comment by teotigraphix** [comment]
I have to recheck this in the tests, it might actually be fixed, if not I will show you something that would die.

**Comment by teotigraphix** [comment]
I am using this;

caustic/create 8bitsynth 8bitsynth 3
caustic/3/expression 1 (35/t<<t)
caustic/3/expression 0 t/57-t*136
/caustic/save_song @C:\Users\Graphix\Desktop\8bit

The Caustic App loads the presets BUT I cannot query them using;

/caustic/3/expression 0

The query just returns ""

**Comment by teotigraphix** [comment]
Rej this seems to be an issue with the expression query. When I load welcome to caustic and save it, it loads fine in Caustic 3.2 app. But whne I "JUST" call a query

```
/caustic/3/expression 0
```

This happens in the app after I save it;

Do you have something reversed in your OSC parsing for this?

![capture](https://cloud.githubusercontent.com/assets/226417/17667206/e65bdd78-62d1-11e6-8525-1b11bc451be1.PNG)

**Comment by teotigraphix** [comment]
Fixed
