### ISSUE TITLE
KSSynth OSC

### ISSUE THREAD

**Issue by teotigraphix** [teotigraphix/CausticSDK#54]

**Comment by causticrej** [comment]
the standard preset, note commands should work in the version you have (apart from the spaces bug in load)

other commands which should already be present are:
pre_filter 0.25 .. 0.99
pre_filter_kbtrack 0.0001 ., 0.99
pre_filter_velocity 0.0001 .. 0.99
decay 0 .. 2
volume_out 0 .. 2
mix 0 .. 1 where 0.5 is 50/50 mix of both KS units
invert_mix 0, 1

then to access the two KS units, add either "unit1/" or "unit2/" to the OSC path to then address the unit's parameters:

kb_follow 0, 1
octave -2, -1, 0, 1, 2
semis -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6
cents -50 .. 50
damping 0.001 .. 0.9
damping_kbtrack 0 .. 1
damping_velocity 0 .. 1
invert 0,1
