### ISSUE TITLE
Modular K35 Low Pass OSC

### ISSUE THREAD

**Issue by teotigraphix** [teotigraphix/CausticSDK#56]

**Comment by causticrej** [comment]
These should work in the (3.1) build you have:

To create a K35, use component index 30

parameters are:
cutoff 0.016...1 (filter was unstable below a certain freq value which explains the weird lower limit)
resonance 0.01 .. 0.79 (ditto, stability limits)
cut_mod 0 .. 1
res_mod 0 .. 1
