### ISSUE TITLE
Sequencer - Query inidivdual machines for patterns

### ISSUE THREAD

**Issue by teotigraphix** [teotigraphix/CausticSDK#64]
Ability to query individual machine track's song patterns in the song sequencer.

/caustic/sequencer/pattern_event [machine_index]

Returns a string of patterns just like the main one.

**Comment by causticrej** [comment]
Ok, I've added that. Now you said "just like the main one" so I've left in the machine index as part of the  individual pattern packet, even though it's implied by the "machine_index" parameter. 

Let me know if you'd rather have the response changed to omit it.

**Comment by teotigraphix** [comment]
Impl
