### ISSUE TITLE
Missing Modular component OSC (3)

### ISSUE THREAD

**Issue by teotigraphix** [teotigraphix/CausticSDK#65]
I don't have OSC for;
- Machine Input 
- Vintage Ladder LP (x2)
- Oscilloscope

Need the osc parameters and type number for each.

**Comment by causticrej** [comment]
I assume you're also missing the K35 LP so I've included those too. You'll need a new lib for these.

First, type numbers:

Vintage ladder: 27
Oscilloscope: 28
Machine input: 29
K35 lowpass: 30

Params:

Machine input
source [0..15]
send_notes [0,1]
out_gain [0..2]

Vintage Ladder (these should already work in your build):
cutoff [0..1]
resonance [0.. 0.885]
cut_mod [0..1]
res_mod [0..1]

Oscilloscope:
zoom [0, 1, 2, 3, 4, 5]
in_gain [0..4]
trig [0,1]  <- this one is inverted from what you'd expect, like all the other switches :-(

K35 lowPass:
cutoff [0.016 .. 1]
resonance [0.01 .. 0.79]
cut_mod [0..1]
res_mod [0..1]

**Comment by teotigraphix** [comment]
Impl
