### ISSUE TITLE
Preset save needs to use path's File name when using @

### ISSUE THREAD

**Issue by teotigraphix** [teotigraphix/CausticSDK#66]
![vsdfsdf](https://cloud.githubusercontent.com/assets/226417/15211491/78135642-1809-11e6-808a-5471f259b9e1.PNG)

**Comment by causticrej** [comment]
Need more info, what's a "simple name"?

**Comment by teotigraphix** [comment]
When I save a preset, sometimes your code internally names it with the native file path. So when you load that preset in Caustic, the preset name is like C:/foo/bar... instead of the file name.

So simple name is the file name I passed to the save as preset command.

**Comment by teotigraphix** [comment]
Thinking about this again, you must have in your code that your display text in the preset label uses the argument passed to save_preset.

Sine I am now passing a full native Path, you are using that as the display label and it shows instead of just the file name.

**Comment by teotigraphix** [comment]
Fixed
