### ISSUE TITLE
SawSynth OSC

### ISSUE THREAD

**Issue by teotigraphix** [teotigraphix/CausticSDK#67]

**Comment by causticrej** [comment]
MAP_NAME_TO_CONTROL("osc_waveform", OSC_TYPE_SELECTOR);    values: [0, 1, 2]
  MAP_NAME_TO_CONTROL("osc_detune", OSC_DETUNE_SLIDER);
  MAP_NAME_TO_CONTROL("osc_mix", OSC_MIX_SLIDER);
  MAP_NAME_TO_CONTROL("osc_width", OSC_WIDTH_KNOB);
  MAP_NAME_TO_CONTROL("pitch_env_amount", PITCH_ENV_AMOUNT_KNOB);  range -1..1
  MAP_NAME_TO_CONTROL("pitch_env_time", PITCH_ENV_TIME_KNOB);  range [0 .. 1.414]
  MAP_NAME_TO_CONTROL("lfo_target", LFO_TARGET_SELECTOR); [0,1,2,3,4,5]
  MAP_NAME_TO_CONTROL("lfo_rate", LFO_RATE_KNOB);   values: [0,1,2,3,4,5,6,7,8,9,10,11,12]
  MAP_NAME_TO_CONTROL("lfo_depth", LFO_DEPTH_KNOB);
  MAP_NAME_TO_CONTROL("filter_type", FILTER_TYPE_SELECTOR); values [0,1,2,3]
  MAP_NAME_TO_CONTROL("filter_cutoff", FILTER_CUTOFF_SLIDER);
  MAP_NAME_TO_CONTROL("filter_resonance", FILTER_RES_SLIDER); range [0.. 0.9]
  MAP_NAME_TO_CONTROL("filter_env_amount", FILTER_ENVAMOUNT_KNOB);  range [-1 .. 1]
  MAP_NAME_TO_CONTROL("filter_kbtrack", FILTER_KBTRACK_KNOB);
  MAP_NAME_TO_CONTROL("filter_attack", FILTER_ATTACK_SLIDER); range [0 .. 1.75]
  MAP_NAME_TO_CONTROL("filter_decay", FILTER_DECAY_SLIDER); range [0 .. 1.75]
  MAP_NAME_TO_CONTROL("filter_sustain", FILTER_SUSTAIN_SLIDER);
  MAP_NAME_TO_CONTROL("filter_release", FILTER_RELEASE_SLIDER);  range [0 .. 1.75]
  MAP_NAME_TO_CONTROL("volume_attack", VOLUME_ATTACK_SLIDER); range [0 .. 1.75]
  MAP_NAME_TO_CONTROL("volume_decay", VOLUME_DECAY_SLIDER); range [0 .. 1.75]
  MAP_NAME_TO_CONTROL("volume_sustain", VOLUME_SUSTAIN_SLIDER);
  MAP_NAME_TO_CONTROL("volume_release", VOLUME_RELEASE_SLIDER);   range [0 .. 1.75]
  MAP_NAME_TO_CONTROL("volume_out", VOLUME_KNOB);
  MAP_NAME_TO_CONTROL("pitch_bend", PITCHBEND_WHEEL);
