### ISSUE TITLE
Octaver OSC

### ISSUE THREAD

**Issue by teotigraphix** [teotigraphix/CausticSDK#68]

**Comment by causticrej** [comment]
MAP_NAME_TO_CONTROL("minus1_gain", M1GAIN_KNOB);   range 0..2
  MAP_NAME_TO_CONTROL("minus1_tone", M1TONE_KNOB); range 0..2 .. 1
  MAP_NAME_TO_CONTROL("plus1_gain", P1GAIN_KNOB);  range 0..2
  MAP_NAME_TO_CONTROL("plus1_tone", P1TONE_KNOB);  range 0.3.. 1.f
  MAP_NAME_TO_CONTROL("dry", DRY_KNOB);
  MAP_NAME_TO_CONTROL("bypass", BYPASS_BUTTON);
