### ISSUE TITLE
AutoPan OSC

### ISSUE THREAD

**Issue by teotigraphix** [teotigraphix/CausticSDK#71]

**Comment by causticrej** [comment]
MAP_NAME_TO_CONTROL("depth", DEPTH_KNOB);
  MAP_NAME_TO_CONTROL("rate", RATE_KNOB);
  MAP_NAME_TO_CONTROL("smooth", SMOOTH_KNOB);
  MAP_NAME_TO_CONTROL("bypass", BYPASS_BUTTON);
