### ISSUE TITLE
Merge Rack to Instrument

### ISSUE THREAD

**Issue by teotigraphix** [teotigraphix/CausticSDK#72]
Question, could this be targeted with OSC?

I have a couple apps that use/ can use this "bounce down" feature and having it controlled on your side could save me huge amounts of pain.

I have something that works kind of like this but is is a huge amount of code that is half baked.

If it could be done, then I could use an OSC command that monitored to progress so I would know when the pcmsynth preset was created.

**Comment by causticrej** [comment]
I'm not sure about this one. This is sorta like a little OSC app inside the app. Definitely not what I'd prioritize first in this list. (it's a lot of work)

**Comment by teotigraphix** [comment]
Yeah, I get taht so my question is more "how" you do it. If I was and have written something like this, I have to clear the song sequencer, add patterns, export loop and then re-add the original song patterns.

Do you get what I mean? Are you using some back door code(to get around removing sequencer patterns to export) or actually using OSC that I have to do it?

I would also and have had to make fake patterns for the export. This is what I was getting at, there is no "off screen buffer" for me to do stuff like this.

**Comment by causticrej** [comment]
I'm triggering notes to play and capturing the output. No special backdoor but obviously if you were to replicate it, you'd have to write your own WAV capture code at the Java level. Should be easy enough, to trigger it on/off and write to WAV, I'm sure there are classes for that.
