### ISSUE TITLE
Rack save_song, save_preset allow the file extension

### ISSUE THREAD

**Issue by teotigraphix** [teotigraphix/CausticSDK#76]
Can you just make these all require the extension for the @ save as call? Since I deal with File objects, I am always trimming the extension off and it's getting really complicated.

**Comment by causticrej** [comment]
ok, I think I gave you the choice at the time and you didn't have a preference. I'm happy to set it to require the ext.

**Comment by teotigraphix** [comment]
Yeah you did but now I use File objects and it became a pain in the ass. :)

**Comment by causticrej** [comment]
ok, I've changed them all.
