### ISSUE TITLE
Rack save progress

### ISSUE THREAD

**Issue by teotigraphix** [teotigraphix/CausticSDK#77]
Can you make a save progress like you did for wav export? I am running into synchronization issues now that I am starting to save larger files and I need to know when the whole .caustic file has been fully written to disk.

**Comment by causticrej** [comment]
I can get you a 0 or 100% but I don't have a notion of progress internally myself.

**Comment by teotigraphix** [comment]
Cool, I just need the 100, I can loop a timer the pool it so progress doesn't have to mean anything, it would just be indeterminate. So anytime I call that you will reset the value to 0 and then 100 when finished.

**Comment by causticrej** [comment]
Ok, I've added a "save_progress" cmd you can query from the root

Note that It only works correctly after a "save_file" call as this resets it to "0%". If the save is in progress it returns 0 and returns 1 if the save is complete. If you call it randomly while working, it'll return 1 (100% saved)

**Comment by teotigraphix** [comment]
Thats fine, I will only be checking it in the async command as I am saving the rack

**Comment by teotigraphix** [comment]
Ok, I jsut tested this with the most recent dll you gave me a month or so ago and this is what I get;

```
Write: /caustic/create subsynth synth 0
Write: /caustic/effects_rack/0/0/mode 1
Read: /caustic/effects_rack/1/0/mode -1000000
```

This is a fresh rack and it is still returning invalid, am I doing something wrong?

**Comment by teotigraphix** [comment]
Ok, scratch my last comment, I just got this to work;

```
Write: /caustic/create subsynth synth 0
Write: /caustic/effects_rack/create 0 0 0
Write: /caustic/effects_rack/0/0/mode 1
Read: /caustic/effects_rack/0/0/mode 1
```

**Comment by teotigraphix** [comment]
It seems the issue actually is restoring a file like CAUSTIC STORM.

It doesn't work, do you think it's a backwards compatibility thing with that file?
