### ISSUE TITLE
MasterMixer missing  delay damping hp/lp

### ISSUE THREAD

**Issue by teotigraphix** [teotigraphix/CausticSDK#82]
I don't have the damping's HP/LP toggle command

**Comment by causticrej** [comment]
I've added this, command will be 

delay_damping_type [0,1]   0 is LP

**Comment by teotigraphix** [comment]
Just curious your pattern for delay was; eg for damping

```
/caustic/master/delay/damping
```

So wouldn't it be

```
/caustic/master/delay/damping_type [0,1]
```

I do some funky dynamic majic in the UI and it depends on the root message being `/caustic/master/delay`.

**Comment by causticrej** [comment]
oh, yeah sorry I'll make it so

**Comment by causticrej** [comment]
hmm, well all the other toggles are like that...

delay_sync
delay_feedback_first

no problems with those?

**Comment by causticrej** [comment]
Hmmm, 

MAP_NAME_TO_CONTROL("delay_time", DELAY_TIME_KNOB);
  MAP_NAME_TO_CONTROL("delay_feedback", DELAY_FEEDBACK_KNOB);
  MAP_NAME_TO_CONTROL("delay_damping", DELAY_DAMPING_KNOB);
  MAP_NAME_TO_CONTROL("delay_wet", DELAY_WET_KNOB);
  MAP_NAME_TO_CONTROL("delay_bypass", DELAY_BYPASS_SWITCH);

you sure about that hierarchy?

**Comment by teotigraphix** [comment]
Well you're the boss and it looks like I never got this master part tested because I have all the master settings with a slash.

It's funny, with CausticGuide I was just about to run into this issue then because I have the UI to import Master settings.

**Comment by teotigraphix** [comment]
This is crazy; I just checked my debugger;

```
delay   CMasterDelay (@c4b8f59) 
    [inherited] 
    bypass  false   
    damping 0   
    delay_pan1  0.3478262424468994  
    delay_pan2  -0.38260895013809204    
    delay_pan3  1   
    delay_pan4  -0.9217392206192017 
    delay_pan5  0   
    feedback    0.5608693361282349  
    feedback_first  0   
    loop    1   
    owner   CMasterChannel (@b77ac41)   
    steps   4   
    sync    1   
    time    8   
    wet 0.5 
```

This is loaded and  restored from CAUSTIC STORM, as ju can see I am getting real values from those messages.

Here is the messages I was using

```
Read: /caustic/master/volume 1.1913068294525146
Read: /caustic/master/delay/bypass 0
Read: /caustic/master/delay/damping 0
Read: /caustic/master/delay/feedback 0.5608693361282349
Read: /caustic/master/delay/feedback_first 0
Read: /caustic/master/delay/loop 1
Read: /caustic/master/delay/pan 0 0.3478262424468994
Read: /caustic/master/delay/pan 1 -0.38260895013809204
Read: /caustic/master/delay/pan 2 1
Read: /caustic/master/delay/pan 3 -0.9217392206192017
Read: /caustic/master/delay/pan 4 0
Read: /caustic/master/delay/steps 4
Read: /caustic/master/delay/sync 1
Read: /caustic/master/delay/time 8
Read: /caustic/master/delay/wet 0.5
Read: /caustic/master/reverb/bypass 0
Read: /caustic/master/reverb/diffuse 0.699999988079071
Read: /caustic/master/reverb/dither_echoes 0
Read: /caustic/master/reverb/er_decay 0.25
Read: /caustic/master/reverb/er_gain 1
Read: /caustic/master/reverb/hf_damping 0.1177390068769455
Read: /caustic/master/reverb/pre_delay 0.03136955574154854
Read: /caustic/master/reverb/room_size 0.8032609224319458
Read: /caustic/master/reverb/stereo_delay 1
Read: /caustic/master/reverb/wet 0.2934783101081848
Read: /caustic/master/reverb/stereo_spread 1
Read: /caustic/master/eq/bass 1.4826087951660156
Read: /caustic/master/eq/bassmid_freq 0.5
Read: /caustic/master/eq/bypass 0
Read: /caustic/master/eq/high 1.7504351139068604
Read: /caustic/master/eq/mid 1
Read: /caustic/master/eq/midhigh_freq 0.5
Read: /caustic/master/limiter/attack 0.021299999207258224
Read: /caustic/master/limiter/bypass 0
Read: /caustic/master/limiter/post 1
Read: /caustic/master/limiter/pre 1
Read: /caustic/master/limiter/release 0.25999999046325684
Write: /caustic/master/effect_type 0
```

**Comment by causticrej** [comment]
Ahhh... I just found a bit of code that make them both right:

// Pre filter the input text to turn "module/knob" into "module_knob" for ease of processing
  char\* pszFound = strstr(szOscMsg, "delay/");
  if (pszFound != NULL) pszFound[5] = '_';

**Comment by causticrej** [comment]
so write it the way you want, it'll work

**Comment by teotigraphix** [comment]
Ok, that was a WTF moment for me, I knew I had it working. :)
