### ISSUE TITLE
Android load_preset seems to not be compiled for preset path with spaces

### ISSUE THREAD

**Issue by teotigraphix** [teotigraphix/CausticSDK#84]

**Comment by causticrej** [comment]
I can't see where this is a bug in the code. I checked all instruments. Is this on any instrument in particular or just one?

I'm just parsing the cmd string for the word "load_preset" and grabbing everything after that to pass to the load function. (so not using parsing or separators)

**Comment by teotigraphix** [comment]
I will check again to make sure

**Comment by teotigraphix** [comment]
Ok, I just tested this on Android with Guide and I am loading all the machines with spaces now. I don't know what happened.

Must have been my mess up.
